### ISSUE TITLE
论文的题目是什么

### ISSUE THREAD

**Issue by sunfeng90** [liguge/capsule-network-for-fault-diagnosis#1]
您好，您整个代码对应的论文题目是什么？网上很多关于《[Capsule-network-for-fault-diagnosis》的论文

**Comment by liguge** [comment]
> 您好，您整个代码对应的论文题目是什么？网上很多关于《[Capsule-network-for-fault-diagnosis》的论文

Hello, welcome to follow our work. 

Many papers are basically permutations and combinations. In many papers on capsule network for fault diagnosis, the function of capsule network is basically a classifier, so I will just experiment.（there is no  published paper and it  need not to publish papers)

However, my junior in our team has an improved version of this code that has been accepted by &quot;IEEE Sensors Journal&quot;. It will be linked to the Internet in about a few days. You can refer to it. I will tell you the doi when the time comes.

**Comment by sunfeng90** [comment]
Okay. Thanks a lot.


Good luck to u.


Regards,
Frank


在2022年4月19日 ***@***.***> 写道：

您好，您整个代码对应的论文题目是什么？网上很多关于《[Capsule-network-for-fault-diagnosis》的论文

Hello, welcome to follow our work.

Many papers are basically permutations and combinations. In many papers on capsule network for fault diagnosis, the function of capsule network is basically a classifier, so I will just experiment.（there is no published paper and it need not to publish papers)

However, my junior in our team has an improved version of this code that has been accepted by "IEEE Sensors Journal". It will be linked to the Internet in about a few days. You can refer to it. I will tell you the doi when the time comes.

**Comment by liguge** [comment]
> Okay. Thanks a lot. Good luck to u. Regards, Frank 在2022年4月19日 ***@***.***> 写道： 您好，您整个代码对应的论文题目是什么？网上很多关于《[Capsule-network-for-fault-diagnosis》的论文 Hello, welcome to follow our work. Many papers are basically permutations and combinations. In many papers on capsule network for fault diagnosis, the function of capsule network is basically a classifier, so I will just experiment.（there is no published paper and it need not to publish papers) However, my junior in our team has an improved version of this code that has been accepted by "IEEE Sensors Journal". It will be linked to the Internet in about a few days. You can refer to it. I will tell you the doi when the time comes. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

https://ieeexplore.ieee.org/document/9761239
